[package]
name = "linkleaf"
version = "0.1.0"
edition = "2024"
description = "Local-first protobuf-only link feed manager (linkleaf.v1) with a tiny CLI."
license = "BSD-3-Clause"
repository = "https://github.com/doriancodes/linkleaf"
homepage = "https://github.com/doriancodes/linkleaf"
documentation = "https://docs.rs/linkleaf"
readme = "README.md"
keywords = ["links", "cli", "protobuf", "local-first"]
categories = ["command-line-utilities"]

include = [
    "Cargo.toml",
    "build.rs",
    "src/**",
    "proto/**",
    "templates/**",
    "README.md",
    "LICENSE*",
    "logo.svg",
    "logo-monochrome.svg",
]

[dependencies]
linkleaf-core = { path = "crates/linkleaf-core" }
prost = "0.13"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
time = { version = "0.3", features = [
    "formatting",
    "parsing",
    "macros",
    "local-offset",
] }
askama = "0.12"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.18.0", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3"

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"

[[bin]]
name = "linkleaf"
path = "src/main.rs"

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
strip = "symbols"
panic = "abort"

# Ensure docs.rs builds pick defaults that compile
[package.metadata.docs.rs]
all-features = false
no-default-features = false
